services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # caddy:
  #   build:
  #     context: .
  #     dockerfile: ./docker/caddy/Dockerfile
  #   depends_on:
  #     - django
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: unless-stopped
  #   volumes:
  #     - production_caddy_config:/config
  #     - production_caddy_data:/data
  #     - production_django_media:/var/www/django/media
  #     - production_django_static:/var/www/django/static

volumes:
  local_postgres_data:
    # production_caddy_config:
    # production_caddy_data:
    # production_django_media:
    # production_django_static:
